apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-2
  namespace: kafka
  labels:
    app: kafka-broker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-2
  template:
    metadata:
      labels:
        app: kafka-broker-2
    spec:
      hostname: kafka-broker-2
      containers:
        - env:
            - name: KAFKA_BROKER_ID
              value: '2'
            # - name: KAFKA_ADVERTISED_HOST_NAME
            #   value: kafka-service-2
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service-2.kafka.svc.cluster.local
            # - name: KAFKA_ZOOKEEPER_CONNECT
            #   value: zookeeper-service:2181
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service.kafka.svc.cluster.local:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9093
            # - name: KAFKA_ADVERTISED_LISTENERS
            #   value: PLAINTEXT://kafka-service-2:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service-2.kafka.svc.cluster.local:9093
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          name: kafka-broker-2
          ports:
            - containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-2
  namespace: kafka
  labels:
    app: kafka-broker-2
spec:
  ports:
    - name: kafka-broker-2-port
      protocol: TCP
      port: 9093
      targetPort: 9093
  selector:
    app: kafka-broker-2
