apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: brameldering/inventory
      context: typescript-react-node/inventory
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/set-3/*
deploy:
  kubectl: {}
