apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: orbitelco/seed
      context: seeder-service
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/postgres-inv/postgres-config.yaml
    - ./infra/k8s/postgres-inv/postgres-depl-1.yaml
    - ./infra/k8s/postgres-inv/postgres-depl-2.yaml
    - ./infra/k8s/set-1/*
deploy:
  kubectl: {}
