apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: brameldering/seed
      context: typescript-react-node/seeder-service
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: brameldering/inventory
      context: java-spring-boot/inventory
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/spring-boot/*
    - ./infra/k8s/set-1/*
deploy:
  kubectl: {}
