apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: orbitelco/sequences
      context: typescript-react-node/sequences
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: orbitelco/auth
      context: typescript-react-node/auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: orbitelco/products
      context: typescript-react-node/products
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: orbitelco/orders
      context: typescript-react-node/orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: orbitelco/client
      context: typescript-react-node/client
      sync:
        manual:
          - src: /**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/set-2/*
deploy:
  kubectl: {}
