apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: brameldering/sequences
      context: typescript-react-node/sequences
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: brameldering/auth
      context: typescript-react-node/auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: brameldering/products
      context: typescript-react-node/products
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    # - image: brameldering/inventory
    #   context: typescript-react-node/inventory
    #   sync:
    #     manual:
    #       - src: src/**/*.ts
    #         dest: .
    #   docker:
    #     dockerfile: Dockerfile
    - image: brameldering/orders
      context: typescript-react-node/orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: brameldering/client
      context: typescript-react-node/client
      sync:
        manual:
          - src: /**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/set-2/*
deploy:
  kubectl: {}
