apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: orbitelco/auth
          env:
            - name: DEPLOY_ENV
              value: 'kubernetes'
            - name: NODE_ENV
              value: 'development'
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-service:27017/auth'
            # - name: KAFKA_BROKERS
            #   value: kafka-service-1:9092
            - name: KAFKA_BROKERS
              value: kafka-service-1.kafka.svc.cluster.local:9092
            - name: KAFKA_LOG_LEVEL
              value: WARN
            # - name: KAFKAJS_NO_PARTITIONER_WARNING
            #   value: 1
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: EXPIRES_IN
              value: '1d'
            - name: DEFAULT_RESET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: default-reset-password
                  key: DEFAULT_RESET_PASSWORD_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
