apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-inv-depl # Sets Deployment name
  # namespace: kafka
  labels:
    app: postgres-inv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-inv
  template:
    metadata:
      labels:
        app: postgres-inv
    spec:
      containers:
        - name: postgres-inv
          image: postgres:15.1 # Sets Image
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5432 # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-inv-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-inv-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-inv # Sets service name
  # namespace: kafka
  labels:
    app: postgres-inv # Labels and Selectors
spec:
  ports:
    - name: postgres-inv-port
      protocol: TCP
      port: 5432 # Sets port to run the postgres application
      targetPort: 5432
  selector:
    app: postgres-inv
