apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-inv-config
  # namespace: kafka
  labels:
    app: postgres-inv
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: inventory
