server.port=3000
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database=postgresql
spring.datasource.url=${PG_URI_INVENTORY:jdbc:postgresql://localhost:5432/postgresdb?currentSchema=INVENTORY}
spring.datasource.username=${PG_DB_USERNAME}
spring.datasource.password=${PG_DB_PASSWORD}

# Added logging levels
logging.level.root=WARN
logging.level.org.springframework.kafka=WARN
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig=ERROR

# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
