server.port=3000
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=jdbc:postgresql://inventory-postgres-service:5432/postgresdb?currentSchema=inventory
# spring.datasource.username=admin
# spring.datasource.password=inventory

spring.datasource.url=${PG_URI_INVENTORY:jdbc:postgresql://localhost:5432/postgresdb?currentSchema=INVENTORY}
spring.datasource.username=${PG_DB_USERNAME}
spring.datasource.password=${PG_DB_PASSWORD}

# Added logging levels
logging.level.root=WARN
logging.level.org.springframework.kafka=WARN
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig=ERROR

# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Kafka Configurations
spring.kafka.bootstrap-servers=kafka-service-1.kafka.svc.cluster.local:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

spring.kafka.consumer.group-id=inventory
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

# Spring DevTools configuration
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
