INSERT INTO INVENTORY.PRODUCT (PRODUCT_ID, NAME, BRAND, CATEGORY) VALUES ('PRD-0000000001', 'Airpods Wireless Bluetooth Headphones', 'Apple', 'Electronics');
INSERT INTO INVENTORY.PRODUCT (PRODUCT_ID, NAME, BRAND, CATEGORY) VALUES ('PRD-0000000002', 'iPhone 13 Pro 256GB Memory', 'Apple', 'Electronics');
INSERT INTO INVENTORY.PRODUCT (PRODUCT_ID, NAME, BRAND, CATEGORY) VALUES ('PRD-0000000003', 'Cannon EOS 80D DSLR Camera', 'Cannon', 'Electronics');
INSERT INTO INVENTORY.PRODUCT (PRODUCT_ID, NAME, BRAND, CATEGORY) VALUES ('PRD-0000000004', 'Sony Playstation 5', 'Sony', 'Electronics');
INSERT INTO INVENTORY.PRODUCT (PRODUCT_ID, NAME, BRAND, CATEGORY) VALUES ('PRD-0000000005', 'Logitech G-Series Gaming Mouse', 'Logitech', 'Electronics');
INSERT INTO INVENTORY.PRODUCT (PRODUCT_ID, NAME, BRAND, CATEGORY) VALUES ('PRD-0000000006', 'Amazon Echo Dot 3rd Generation', 'Amazon', 'Electronics');


INSERT INTO INVENTORY.QUANTITY (PRODUCT_ID, QUANTITY, HAS_SERIAL_NUMBERS) VALUES ('PRD-0000000001', 100, FALSE);
INSERT INTO INVENTORY.QUANTITY (PRODUCT_ID, QUANTITY, HAS_SERIAL_NUMBERS) VALUES ('PRD-0000000002', 12, FALSE);
INSERT INTO INVENTORY.QUANTITY (PRODUCT_ID, QUANTITY, HAS_SERIAL_NUMBERS) VALUES ('PRD-0000000003', 1, FALSE);
INSERT INTO INVENTORY.QUANTITY (PRODUCT_ID, QUANTITY, HAS_SERIAL_NUMBERS) VALUES ('PRD-0000000004', 3, FALSE);
INSERT INTO INVENTORY.QUANTITY (PRODUCT_ID, QUANTITY, HAS_SERIAL_NUMBERS) VALUES ('PRD-0000000005', 0, FALSE);
INSERT INTO INVENTORY.QUANTITY (PRODUCT_ID, QUANTITY, HAS_SERIAL_NUMBERS) VALUES ('PRD-0000000006', 0, FALSE);

-- INSERT INTO INVENTORY.SERIAL_NUMBER (PRODUCT_ID, SERIAL_NUMBER) VALUES ('PRD-0000000001', '1234567890');
