apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: orbitelco/products
          env:
            - name: NODE_ENV
              value: 'development'
            - name: MONGO_URI
              value: 'mongodb://products-mongo-srv:27017/products'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: EXPIRES_IN
              value: '1d'
            - name: CLOUDINARY_CLOUD_NAME
              value: 'dhhfmbqmx'
            - name: CLOUDINARY_SAMPLE_IMAGE_URL
              value: 'https://res.cloudinary.com/dhhfmbqmx/image/upload/v1694085641/lm10qpemqymaoirhhl5a.jpg'
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-api-key
                  key: CLOUDINARY_API_KEY_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-api-secret
                  key: CLOUDINARY_API_SECRET_KEY
            - name: PRODUCTS_PER_PAGE
              value: '12'
---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  type: ClusterIP
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 3000
      targetPort: 3000
