apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-postgres-depl # Sets Deployment name
  # namespace: kafka
  labels:
    app: inventory-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-postgres
  template:
    metadata:
      labels:
        app: inventory-postgres
    spec:
      containers:
        - name: inventory-postgres
          image: postgres:15.1 # Sets Image
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5432 # Exposes container port
          envFrom:
            - configMapRef:
                name: inventory-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: inventory-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-postgres-service # Service name
  # namespace: kafka
  labels:
    app: inventory-postgres # Labels and Selectors
spec:
  ports:
    - name: inventory-postgres-port
      protocol: TCP
      port: 5432 # Sets port to run the postgres application
      targetPort: 5432
  selector:
    app: inventory-postgres
