apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
        - name: seq
          image: orbitelco/seq
          env:
            - name: NODE_ENV
              value: 'development'
            - name: MONGO_URI
              value: 'mongodb://seq-mongo-srv:27017/seq'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: EXPIRES_IN
              value: '1d'
---
apiVersion: v1
kind: Service
metadata:
  name: seq-srv
spec:
  type: ClusterIP
  selector:
    app: seq
  ports:
    - name: seq
      protocol: TCP
      port: 3000
      targetPort: 3000
