apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres # Sets Deployment name
  namespace: kafka
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.1 # Sets Image
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5432 # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data2
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  namespace: kafka
  labels:
    app: postgres # Labels and Selectors
spec:
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432 # Sets port to run the postgres application
      targetPort: 5432
  selector:
    app: postgres
