apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-conduktor-pv-volume # Sets PV's name
  namespace: kafka
  labels:
    type: local # Sets PV's type to local
    app: postgres-conduktor
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/mnt/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-conduktor-pv-claim # Sets name of PVC
  namespace: kafka
  labels:
    app: postgres-conduktor
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: 5Gi # Sets volume size
