apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-conduktor-config
  namespace: kafka
  labels:
    app: postgres-conduktor
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: conduktor
