apiVersion: apps/v1
kind: Deployment
metadata:
  name: seed-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seed
  template:
    metadata:
      labels:
        app: seed
    spec:
      containers:
        - name: seed
          image: orbitelco/seed
          env:
            - name: NODE_ENV
              value: 'development'
            # - name: MONGO_URI_SEQ
            #   value: 'mongodb://seq-mongo-service:27017/seq'
            - name: MONGO_URI_PRODUCTS
              value: 'mongodb://products-mongo-service:27017/products'
            - name: MONGO_URI_AUTH
              value: 'mongodb://auth-mongo-service:27017/auth'
            - name: MONGO_URI_ORDERS
              value: 'mongodb://orders-mongo-service:27017/orders'
            # - name: KAFKA_BROKERS
            #   value: kafka-service-1:9092
            - name: KAFKA_BROKERS
              value: kafka-service-1.kafka.svc.cluster.local:9092
            - name: KAFKA_LOG_LEVEL
              value: WARN
---
apiVersion: v1
kind: Service
metadata:
  name: seed-service
spec:
  type: ClusterIP
  selector:
    app: seed
  ports:
    - name: seed
      protocol: TCP
      port: 3000
      targetPort: 3000
